api/urls.py
# !/usr/bin/env python 3
# encoding: utf-8
# url.py create by zander on 2017/9/6 10:24

from django.conf.urls import url

from . import views, api

urlpatterns = [
    url(r'^translate/$',api.Translation.as_view(), name='translate'),
    url(r'^translatev2/$',api.TranslationV2.as_view(), name='translatev2'),

]

blog/urls.py
# !/usr/bin/env python 3
# encoding: utf-8
# urls.py create by zander on 2017/8/2 12:51

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', view=views.IndexView.as_view(), name="index"),
    url(r'^create$', view=views.create, name="create"),
    # url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<article_id>[0-9]+)/$', views.detail,name="detail")
]

djsite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.shortcuts import render


def index(request):
    return render(request, "todo.html")


urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'^admin/', admin.site.urls),
    url(r'^spider/', include('spider.urls', namespace="spider")),
    url(r'^todo/', include('todo.urls', namespace="todo")),
    url(r'^nlp/', include('nlp.urls', namespace="nlp")),
    url(r'^mining/', include('mining.urls', namespace="mining")),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^api/', include('api.urls', namespace="api")),
]

mining/urls.py
# !/usr/bin/env python 3
# encoding: utf-8
# urls.py create by zander on 2017/7/21 14:51

from django.conf.urls import url

from . import views, api

urlpatterns = [
    url(r'^resource$', view=views.IndexList.as_view(), name='resource'),
    url(r'^spider$', view=views.ProjectList.as_view(), name='spider'),
    url(r'^detail$', view=views.projectDetail, name='detail'),
    url(r'^crawl$', view=views.crawl, name='crawl'),
    url(r'^csv_download$', view=views.csv_download, name='csv_download'),
    url(r'^pic_upload', view=views.pic_upload, name='pic_upload'),
    url(r'^resource_create$', view=api.ResourceCreate.as_view(),name='resource_create'),
    # url(r'^resource_create$', view=api..as_view(),name='resource_create'),
    url(r'^type_list', view=api.TypeList.as_view(),name='type_list'),
    url(r'^type/(?P<pk>[0-9]+)/', view=api.TypeDetail.as_view(),name='type_detail')

]

nlp/urls.py
# !/usr/bin/env python 3
# encoding: utf-8
# urls.py create by zander on 2017/7/11 10:38

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^jieba$', views.sample, name="jieba"),
    url(r'^references', views.references, name="references"),
    url(r'^jieba_app', views.jieba_app, name="jieba_app"),
]

todo/urls.py
# !/usr/bin/env python 3
# encoding: utf-8
# urls.py create by zander on 2017/6/30 11:21
from django.conf.urls import url

from . import views
from . import api

urlpatterns = [
    url(r'^api_test$', views.api_test, name='api_test'),
    url(r'^references$', views.references, name='references'),
    url(r'^nlp', views.api_test, name='nlp'),
    url(r'^music$', views.music, name='music'),
    url(r'^css', views.css, name='css'),
    url(r'^q$', views.question, name='question'),
    url(r'^keyboard$', views.keyboard, name='keyboard'),
    url(r'^search$', views.todoFilter, name='search'),
    url(r'^words_hunter', views.words_hunter, name='words_hunter'),
    url(r'^api_words/$', api.WordsViewSet.as_view(),name="api_words"),
    url(r'^words/(?P<pk>[0-9]+)/$', api.WordDetail.as_view(),name="api_detail"),
    url(r'^words_random/$', api.WordsRandom.as_view(),name="words_random"),
    url(r'^questions/$', api.QuestionList.as_view(),name="questions"),
    url(r'^question/(?P<pk>[0-9]+)/$', api.GetOrUpdateQuestion.as_view(),name="get_update_question"),
    url(r'^last_question/$', api.LastQuestion.as_view(),name="last_question"),
    url(r'^create_question/$', api.CreateQuestion.as_view(),name="create_question"),
    url(r'^list/$', api.TodoList.as_view(),name="todo_list"),
    url(r'^new_todo/$', api.NewTodo.as_view(),name="new_todo"),
    url(r'^(?P<pk>[0-9]+)/$', api.GetOrUpdateTodo.as_view(),name="get_update_todo"),
    url(r'^delete_todo/(?P<pk>[0-9]+)/$', api.DeleteTodo.as_view(),name="delete_todo"),
]

templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title|default:_("Miaow")  }}</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static "frame/bootstrap-3.3.7-dist/css/bootstrap.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "frame/Font-Awesome-3.2.1/css/font-awesome.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}">
    <link rel="icon" href="{% static "imgs/favicon.ico" %}">
    {% block style %}


    {% endblock %}

</head>
<body class="{% block body_class %}custom-background{% endblock %}">
{% csrf_token %}
{% block header %}
{% include "base/header.html" %}
{% endblock %}

{% block mainbody %}

{% endblock %}

{% load static %}
<script src="{% static "js/jquery-3.2.1.min.js" %}"></script>
<script src="{% static "frame/bootstrap-3.3.7-dist/js/bootstrap.js" %}"></script>
<script src="{% static "js/vue.min.js" %}"></script>
{#<script src="{% static "js/vee-validate.js" %}"></script>#}
<script src="{% static "js/main.js" %}"></script>
<script src="{% static "js/admin.js" %}"></script>
<script src="{% static "js/vue-resource.js" %}"></script>
<script>
    Vue.options.delimiters  = ["${","}"];
{#    Vue.use(VeeValidate);#}
    Vue.http.headers.common['X-CSRFToken']  = $("[name='csrfmiddlewaretoken']").val();
    Vue.http.options.emulateJSON = true;
</script>
{% block script %}{% endblock %}
{% block footer %}{% endblock %}
</body>
</html>

templates/base/header.html
<header>
    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">Miaow</a>
            </div>
            <div>
                <span class="pull-right" style="min-width: 20%;min-height: 1px"></span>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/admin">Admin</a></li>
                    <li class="dropdown">
                        <a href="javascript:" class="dropdown-toggle" data-toggle="dropdown">
                            API
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
{#                            <li><a href="{% url "todo:questions" %}" target="_blank">Question</a></li>#}
                            <li><a href="{% url "api:translate" %}" target="_blank">有道翻译</a></li>
{#                            <li><a href="{% url "todo:last_question" %}" target="_blank">Last Question</a></li>#}
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:" class="dropdown-toggle" data-toggle="dropdown">
                            Todo
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url "todo:api_words" %}" target="_blank">API_words</a></li>
                            <li><a href="{% url "todo:words_hunter" %}">Words Hunter</a></li>
                            <li><a href="{% url "todo:question" %}">Question</a></li>
                            <li><a href="{% url "todo:keyboard" %}">Keyboard</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:" class="dropdown-toggle" data-toggle="dropdown">
                            笔记
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url "blog:index" %}">列表</a></li>
                            <li><a href="{% url "blog:create" %}">新建</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:" class="dropdown-toggle" data-toggle="dropdown">
                            数据分析
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url "mining:resource" %}">资源收集</a></li>
                            <li><a href="{% url "spider:test" %}">测试</a></li>
                            <li><a href="{% url "mining:spider" %}">爬虫</a></li>
                            <li><a href="{% url "todo:music" %}">音乐可视化</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:" class="dropdown-toggle" data-toggle="dropdown">
                            Test
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url "todo:api_test" %}">API_Test</a></li>
                            <li><a href="{% url "todo:music" %}">Music</a></li>
                        </ul>
                    </li>
{#                    <li class="dropdown">#}
{#                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">#}
{#                            Spider#}
{#                            <b class="caret"></b>#}
{#                        </a>#}
{#                        <ul class="dropdown-menu">#}
{#                            <li><a href="{% url "spider:index" %}">Index</a></li>#}
{#                            <li><a href="{% url "spider:test" %}">Test</a></li>#}
{#                            <li><a href="{% url "spider:add" %}">Add</a></li>#}
{#                            <li><a href="{% url "spider:list" %}">List</a></li>#}
{#                            <li class="divider"></li>#}
{#                            <li><a href="#">分离的链接</a></li>#}
{#                            <li class="divider"></li>#}
{#                            <li><a href="#">另一个分离的链接</a></li>#}
{#                        </ul>#}
{#                    </li>#}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            NLP
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url "nlp:jieba" %}">Jieba</a></li>
                            <li class="divider"></li>
                            <li><a href="{% url "nlp:references" %}">参考资料</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>