api/urls.py
# !/usr/bin/env python 3
# encoding: utf-8
# url.py create by zander on 2017/9/6 10:24

from django.conf.urls import url

from . import views, api

urlpatterns = [
    url(r'^translate/$',api.Translation.as_view(), name='translate'),
    url(r'^translatev2/$',api.TranslationV2.as_view(), name='translatev2'),

]

djsite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.shortcuts import render


def index(request):
    return render(request, "todo.html")


urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'^admin/', admin.site.urls),
    url(r'^spider/', include('spider.urls', namespace="spider")),
    url(r'^todo/', include('todo.urls', namespace="todo")),
    url(r'^nlp/', include('nlp.urls', namespace="nlp")),
    url(r'^mining/', include('mining.urls', namespace="mining")),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^api/', include('api.urls', namespace="api")),
]

nlp/urls.py
# !/usr/bin/env python 3
# encoding: utf-8
# urls.py create by zander on 2017/7/11 10:38

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^jieba$', views.sample, name="jieba"),
    url(r'^references', views.references, name="references"),
    url(r'^jieba_app', views.jieba_app, name="jieba_app"),
]

todo/urls.py
# !/usr/bin/env python 3
# encoding: utf-8
# urls.py create by zander on 2017/6/30 11:21
from django.conf.urls import url

from . import views
from . import api

urlpatterns = [
    url(r'^api_test$', views.api_test, name='api_test'),
    url(r'^references$', views.references, name='references'),
    url(r'^nlp', views.api_test, name='nlp'),
    url(r'^music$', views.music, name='music'),
    url(r'^css', views.css, name='css'),
    url(r'^q$', views.question, name='question'),
    url(r'^keyboard$', views.keyboard, name='keyboard'),
    url(r'^search$', views.todoFilter, name='search'),
    url(r'^words_hunter', views.words_hunter, name='words_hunter'),
    url(r'^api_words/$', api.WordsViewSet.as_view(),name="api_words"),
    url(r'^words/(?P<pk>[0-9]+)/$', api.WordDetail.as_view(),name="api_detail"),
    url(r'^words_random/$', api.WordsRandom.as_view(),name="words_random"),
    url(r'^questions/$', api.QuestionList.as_view(),name="questions"),
    url(r'^question/(?P<pk>[0-9]+)/$', api.GetOrUpdateQuestion.as_view(),name="get_update_question"),
    url(r'^last_question/$', api.LastQuestion.as_view(),name="last_question"),
    url(r'^create_question/$', api.CreateQuestion.as_view(),name="create_question"),
    url(r'^list/$', api.TodoList.as_view(),name="todo_list"),
    url(r'^new_todo/$', api.NewTodo.as_view(),name="new_todo"),
    url(r'^(?P<pk>[0-9]+)/$', api.GetOrUpdateTodo.as_view(),name="get_update_todo"),
    url(r'^delete_todo/(?P<pk>[0-9]+)/$', api.DeleteTodo.as_view(),name="delete_todo"),
]

todo/models.py
from django.db import models


# Create your models here.


class Todo(models.Model):
    content = models.CharField(verbose_name="Content", max_length=255)
    # in_time = models.DateTimeField(verbose_name="In Time", auto_created=True)
    create_time = models.DateTimeField(verbose_name="Create", auto_now_add=True)
    # edit_time = models.DateTimeField(verbose_name="Edit Time", auto_now=True)
    # level = models.SmallIntegerField(verbose_name="Level", default=3)
    state = models.BooleanField(verbose_name="State", default=False)
    # remarks = models.CharField(verbose_name="Remarks", max_length=1024, null=True)


class Question(models.Model):
    # 未make ，make之后删除该注释，，长度限制(i)，，markdown(i)
    desc = models.CharField(verbose_name="问题", max_length=255)
    in_time = models.DateTimeField(verbose_name="添加时间", auto_now_add=True)
    re_time = models.DateTimeField(verbose_name="解决时间", auto_now=True)
    state = models.BooleanField(verbose_name="状态", default=False)
    answer = models.CharField(verbose_name="答案", max_length=255,null=True,blank=True)

    # class Child(models.Model):
    #     parent = models.ForeignKey(Todo,verbose_name="Todo")
    #     content = models.CharField(verbose_name="Content", max_length=255)

    #
    # class Article(models.Model):
    #     content = models.TextField(verbose_name="内容", max_length=2048)
    #     in_date = models.TimeField(verbose_name="创建日期", auto_created=True)
    #     type = models.ForeignKey(ArticleType, verbose_name="类别")
    #
    #
    # class ArticleType(models.Model):
    #     name = models.CharField(verbose_name="分类名称", max_length=16)
    #     intro = models.CharField(verbose_name="简介", max_length=32, null=True)


class Words(models.Model):
    word = models.CharField(verbose_name="word", max_length=32, unique=True)
    level = models.IntegerField(verbose_name="level", default=1)
    hp = models.IntegerField(verbose_name="hp", default=5)

nlp/views.py
from django.shortcuts import render
from django.http import HttpResponse
import jieba
import jieba.posseg as pseg
import jieba.analyse
import json

# Create your views here.


def sample(request):
    return render(request, "nlp/jieba.html")


def references(request):
    return render(request, "nlp/references.html")


def jieba_app(request):
    if request.is_ajax():
        content = request.POST['content']
        topk = 20


        words = jieba.cut(content) # 分词
        words_p = pseg.cut(content) # 词性标注
        key = jieba.analyse.extract_tags(content, topK=topk) # TDIDF

        result = {'cut': list(words), 'pseg': ["{}/{}".format(w.word, w.flag) for w in words_p], 'key': list(key)}

        return HttpResponse(json.dumps(result,ensure_ascii=False))

todo/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from .models import Todo, Words
from django.http import HttpResponse
import json
# Create your views here.


class IndexView(generic.ListView):
    template_name = "todo.html"
    context_object_name = "todo_list"

    def get_queryset(self):
        # fil = {
        #
        # }
        # if 'state' in self.request.GET:
        #     s = self.request.GET['state']
        #     fil['state'] = s == 'true'
        # if 'level' in self.request.GET:
        #     fil['level'] = self.request.GET['level']
        return Todo.objects.order_by('-create_time').all()


# API methods


def todoFilter(request):

    if request.is_ajax():
        # Todo.objects.filter().all()
        return HttpResponse()


def words_hunter(request):
    return render(request,"todo/words.html")


def api_test(request):

    return render(request,"todo/api_test.html")


def nlp(request):
    return render(request, "todo/nlp.html")


def references(request):
    return render(request, "todo/references.html")


def music(request):
    return render(request, "todo/music.html")


def question(request):
    return render(request,"todo/1-Q.html")


def keyboard(request):
    return  render(request, "todo/keyboard.html")

def css(request):
    return  render(request, "todo/css.html")

todo/templates/todo/1-Q.html
{% extends "base/base.html" %}

{% block style %}
<style>

</style>
{% endblock %}

{% block body_class %}

{% endblock %}

{% block mainbody %}
<section class="container" id="vueApp">
    <div class="row">
        <div class="col-md-6 col-md-offset-3" style="text-align:center">
            <h1>Question</h1>
            <hr>
            <p style="width: 100%;margin-bottom: 200px">${ question?question.desc:"no data" }</p>

            <button type='button' data-toggle="modal" data-target="#answer" :disabled="!question" class="btn btn-info">Answer This</button>
            <div class="modal fade" id="answer" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                &times;
                            </button>
                            <h4 class="modal-title" id="myModalLabel">
                                Answer
                            </h4>
                        </div>
                        <div class="modal-body">
                            <input type="text" placeholder="answer" class="form-control" spellcheck="false" v-model="question.answer" @keyup.13="update">
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">cancel</button>
                            <button type="button" class="btn btn-primary" @click="update">ok</button>
                        </div>
                    </div>
                </div>
            </div>
            <button type='button' data-toggle="modal" data-target="#newQuestion" class="btn btn-info">New Question</button>
            <div class="modal fade" id="newQuestion" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                &times;
                            </button>
                            <h4 class="modal-title" id="myModalLabel">
                                New Question
                            </h4>
                        </div>
                        <div class="modal-body">
                            <input type="text" placeholder="new question" class="form-control" spellcheck="false" v-model="n_question.desc" @keyup.13="create">
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">cancel</button>
                            <button type="button" class="btn btn-primary" @click="create">ok</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block script %}
<script>
let app = new Vue({
    el:"#vueApp",
    mounted:function () {
        this.last_question()
    },
    data:{
        question:"",
        n_question:{
            desc:""
        }
    },
    methods:{
        create:function () {
            let that = this;
            if(!that.n_question.desc){
                return
            }
            that.$http.post("{% url "todo:create_question" %}",that.n_question)
                .then(res=>{
                    that.question = res.body;
                    $("#newQuestion").modal("hide")
                })
        },
        update:function () {
            let that = this;
            if(!that.question.answer){
                return
            }
            that.question.state = true;
            that.$http.post("question/{}/".format(that.question.id),that.question)
                .then(res=>{
                    that.last_question();
                    $("#answer").modal("hide")
                })
        },
        last_question:function () {
            let that = this;
            this.$http.get("{% url "todo:last_question" %}")
                .then(res=>{
                    if(res.body.length){
                      that.question = res.body[0]
                    }else{
                        that.question = ""
                    }
            })
        }
    }

})
</script>
{% endblock %}

todo/templates/todo/api_test.html
{% extends "base/base.html" %}

{% block mainbody %}
    <section class="container" id="app">
        <div class="row">
            <div class="panel panel-success">
                <div class="panel-heading">
                    API调试工具
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-2">
                            <select title="" name="" class="form-control" id="" v-model="type">
                                <option v-for="method in methods">${ method }</option>
                            </select>
                        </div>
                        <div class="col-md-8">
                            <input type="text" title="" placeholder="url" v-model="url" class="form-control"/>
                        </div>
                        <div class="col-md-2">
                            <div class="btn-group">
                                <button type="button" class="btn btn-primary" v-on:click="send">AJAX</button>
                                <button type="button" class="btn btn-primary" v-on:click="request">Request</button>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="panel panel-info">
                <div class="panel-heading">
                    Data
                </div>
                <div class="panel-body">


                    <div class="row">
                        <div class="col-md-6">
                        <div class="form-group">
                            <label for="">Data</label>
                            <textarea title="" style="resize: vertical" rows="15" v-model="ajax_data" class="form-control"></textarea>
                        </div>
                    </div>
                        <div class="col-md-6">
                        <div class="form-group">
                            <label for="">Response</label>
                            <textarea style="resize: vertical" class="form-control" title="" rows="15" v-model="response"></textarea>
                        </div>
                    </div>
                    </div>
                    <div class="row">
                        <div class="col-md-2">
                            <div class="form-group">
                                <label for="">Content-Type</label>
                                <select name="" id=""  v-model="contentType" class="form-control">
                                    <option value=""></option>
                                    <option value="application/json">application/json</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

{% block footer %}
<script>
    let app = new Vue({
        el:"#app",
        data:{
            url:"http://localhost:8082/api/area!list.action",
            methods:['GET', 'POST'],
            contentType:"",
            type:"GET",
            ajax_data:`
{
    "province":"北京市",
    "city":"西城区"
}
            `,
            response:""
        },
        methods:{
            send:function () {
                let that = this;
                let d;
                if (that.ajax_data){
                    d = JSON.parse(that.ajax_data);
                }else{
                    d = {}
                }
                if(that.contentType === "application/json"){
                    d = JSON.stringify(d)
                }

                $.ajax({
                    url:that.url,
                    type:that.type,
                    data:d,
                    contentType:that.contentType,
                    success:function (res) {
                        that.response = res;
                    },
                    error:function (res) {
                        that.response = res;
                    }
                })


            },
            request:function () {
                let that = this;
                window.alert("暂未实现")

            }
        }

    })

</script>
{% endblock %}

todo/templates/todo/color.html
{% extends "base/base.html" %}

todo/templates/todo/css.html
{% extends "base/base.html" %}

{% block style %}
<style>
.block{
    margin: 0 10px 20px 10px;
    float: left;
}
.one{
    border: 1px solid greenyellow;
    border-radius: 50%;
    width: 260px;
    height: 260px;
}
.two{
    width: 260px;
    height: 260px;
    border-radius: 100% 0 0 0;
    border-top: 130px solid chartreuse;
    border-left: 1px solid chartreuse;
}
.three{
    width: 260px;
    height: 260px;
    border-bottom: 260px solid #62e08b;
    border-left: 130px solid transparent;
    border-right: 130px solid transparent;
}
.four{
    width: 260px;
    height: 260px;
    transform: rotate(45deg);
    background-color: turquoise;
}
.five{
    width: 250px;
    height: 250px;
{#    border-bottom: 10px solid greenyellow;#}
{#    border-left: 10px solid darkgreen;#}
    border-radius: 50%;
    box-shadow:
            -10px 0 turquoise, /*左边阴影*/
    10px 0  chartreuse, /*右边阴影*/
    0 -10px  turquoise, /*顶部阴影*/
    0 10px  chartreuse; /*底边阴影*/
{#    -20px -10px red,#}
{#    20px -10px red,#}
{#    -10px -20px red,#}
{#    -10px 20px red;#}
}

</style>
{% endblock %}
{% block body_class %}

{% endblock %}
{% block mainbody %}
    <section class="container">
    <div class="one block">

    </div>
    <div class="two block">

    </div>
    <div class="three block">

    </div>
    <div class="block" style="overflow: hidden">
        <div class="four"></div>
    </div>

    <div class="five block"></div>
    </section>
{% endblock %}

todo/templates/todo/jieba.html
{% extends "base/base.html" %}

todo/templates/todo/keyboard.html
{% extends "base/base.html" %}

{% block style %}
<style>
body{
    margin: 0;
}
canvas{
    width: 100%;
    height: 100%;
}
</style>
{% endblock %}

{% block body_class %}

{% endblock %}

{% block header %}

{% endblock %}

{% block mainbody %}

{% endblock %}

{% block script %}
    {% load staticfiles %}
    <script src="{% static "js/three.js" %}"></script>

    <script>
        let scene = new THREE.Scene();

        let camera = new THREE.PerspectiveCamera( 75, window.innerWidth / window.innerHeight, 0.1, 1000 );

        let renderer = new THREE.WebGLRenderer();
        renderer.setSize( window.innerWidth, window.innerHeight );
        document.body.appendChild( renderer.domElement );

        let geometry = new THREE.BoxGeometry( 1, 1, 1 );
        let material = new THREE.MeshBasicMaterial( { color: 0x00ff00 } );
        let cube = new THREE.Mesh( geometry, material );
        scene.add( cube );

        camera.position.z = 5;

        function animate() {
            requestAnimationFrame( animate );
            cube.rotation.x += 0.1;
            cube.rotation.y += 0.1;
            renderer.render( scene, camera );
        }
        animate();
    </script>
{% endblock %}

todo/templates/todo/music.html
{% extends "base/base.html" %}

{% block style %}
    <meta name="description" content="HTML5 Audio Spectrum Visualizer">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        html, body {
            margin: 0;
            font-family: arial, "Microsoft YaHei";
            background-color: #272822;
            color: #FEFEFE;
        }
        #fileWrapper{
            transition:all 0.5s ease;
        }
        #fileWrapper:hover{
            opacity: 1!important;
        }

        #visualizer_wrapper{
            text-align: center;
        }
        footer{
            position: fixed;
            bottom: 2px;
            color:#aaa;
        }
    </style>
{% endblock %}

{% block header %}

{% endblock %}

{% block mainbody %}
    <div id="wrapper">
        <div id="fileWrapper" class="file_wrapper">
            <div class="form-inline" style="background-color: inherit">
                <label for="uploadedFile" class="control-label">Drag&drop or select a file to play:</label>
                <input type="file" id="uploadedFile" class="form-control" style="background-color: inherit;border: none"/>
            </div>
        </div>
        <div id="visualizer_wrapper">
            <canvas id='canvas' width="800" height="350"></canvas>
        </div>

        <div style="text-align: center; margin-top: 40px;font-size: 2.5em">
            <div id="info">
                HTML5 Audio API showcase | An Audio Viusalizer
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}
{% load static %}
        <script type="text/javascript" src="{% static "js/html5_audio_visualizer.js" %}"></script>
    <script>
        $("body").removeClass("custom-background")
    </script>
{% endblock %}

todo/templates/todo/nlp.html
{% extends "base/base.html" %}

todo/templates/todo/references.html
{% extends "base/base.html" %}
{% block style %}
    <style>
    thead{
        font-size: 1.3em;
    }
    tr > th {
        width: 10%;
    }
    </style>
{% endblock %}

{% block header %}

{% endblock %}

{% block body_class %}

{% endblock %}

{% block mainbody %}
    <section id="vueApp" class="container">
    <table class="">
        <caption><h3>机器学习</h3></caption>
    <thead>
    <tr>
        <th>链接</th>
        <th>类型</th>
        <th>简介</th>
    </tr>
    </thead>
    <tbody>
    <tr v-for="item in ml">
        <td><a :href="item.link" target="_blank">${ item.name }</a></td>
        <td>${ item.type }</td>
        <td>${ item.desc }</td>
    </tr>
    </tbody>
    </table>
        <br>
    <table class="">
        <caption><h3>API文档</h3></caption>
    <thead>
    <tr>
        <th>链接</th>
        <th>类型</th>
        <th>简介</th>
    </tr>
    </thead>
    <tbody>
    <tr v-for="item in doc">
        <td><a :href="item.link" target="_blank">${ item.name }</a></td>
        <td>${ item.type }</td>
        <td>${ item.desc }</td>
    </tr>
    </tbody>
    </table>
    </section>
{% endblock %}

{% block footer %}
    <script>


        let app = new Vue({
            el:"#vueApp",
            data:{
                ml:[
                    {link:"https://www.jiqizhixin.com/", name:"机器之心", type:"资讯", desc:"" },
                    {link:"http://www.guokr.com/", name:"果壳网", type:"科学社区", desc:"交流" },
                ],
                doc:[
                    {link:"http://pandas.pydata.org/pandas-docs/stable/",name:"Pandas", type:"文档", desc:""},
                    {link:"https://cn.vuejs.org/v2/api/",name:"Vue.js", type:"文档", desc:""},
                ],

            }
        })
    
    </script>
{% endblock %}

todo/templates/todo/words.html
{% extends "base/base.html" %}

{% block style %}
    <style>
    .audio_play{
        background: none;
        border: none;
        outline: none;
    }
    a:link{
        text-decoration-line: none;
    }
    a:visited{
        text-decoration-line: none;
    }
    a:hover{
        text-decoration-line: none;
    }
    a:active{
        text-decoration-line: none;
    }
    .word:hover .inter{
        display: inline-block;
    }
    .inter{
        display: none;
        border: none;
        background: none;
        float: right;
    }

    </style>
{% endblock %}
{% block body_class %}

{% endblock %}
{% block mainbody %}
    <section class="container" id="vueApp">
        <div class="row">
            <div class="col-md-12">
                <div class="progress">
                    <div class="progress-bar"
                         :class="{'progress-bar-success':health <= 90,'progress-bar-info':health <= 60,'progress-bar-warning':health <= 30,'progress-bar-danger':health <= 10}" role="progressbar" aria-valuenow="60"
                        aria-valuemin="0" aria-valuemax="100" :style="{width: (health>=100?100:health)+'%'}">
                        <span class="">${ health }</span>
                    </div>
                </div>
            </div>
            <div class="col-md-2 col-md-offset-10">
                <label for="">coin:<span>${ coin }</span></label>
                <label for="">hp: <span>${ health }</span></label>
                <button type="button" class="btn btn-info" data-toggle="modal" data-target="#add_word">add</button>
                <div class="modal fade" id="add_word" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                    &times;
                                </button>
                                <h4 class="modal-title" id="myModalLabel">
                                    添加新单词
                                </h4>
                            </div>
                            <div class="modal-body">
                                <input type="text" placeholder="new word" class="form-control" v-model="word" @keyup.13="add_words">
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                                <button type="button" class="btn btn-primary" @click="add_words">确定</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
        <div class="col-md-4 col-md-offset-4">

            <div class="modal fade" id="interpretation" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                        &times;
                                    </button>
                                    <h4 class="modal-title" id="myModalLabel">
                                        ${ interpretation.query }
                                    </h4>
                                </div>
                                <div class="modal-body">
                                    <h5><span v-for="t in interpretation.translation">${ t };</span></h5>
                                    <h5 v-show="interpretation.basic">
                                        美:[ ${ interpretation.basic?interpretation.basic['us-phonetic']:"" } ] <button type="button" class="audio_play" @click="audio_play"><i class="icon-volume-up"></i></button>
                                        <audio id="audio" controls="" style="display:none" name="media" :src="'http://dict.youdao.com/dictvoice?audio='+interpretation.query"></audio>
                                    </h5>
                                    <ul v-show="interpretation.basic">
                                        <li v-for=" ex in interpretation.basic.explains">${ex}</li>
                                    </ul>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
{#                                    <button type="button" class="btn btn-primary">提交更改</button>#}
                                </div>
                            </div>
                        </div>
                    </div>

            <div style="width: 100%;height: 200px;text-align: center;padding: 10px">
                <h1 class="word">
{#                    :href="'https://translate.google.cn/#en/zh-CN/'+arena.word" #}
                    <a  type="button"  target="_blank" data-toggle="modal" data-target="#interpretation">
                        ${ arena.word }
                    </a>
                </h1>
                <hr>
                <h4>level: <span>${ "♔".repeat(arena.level) }</span></h4>
                <h4>hp: <span style="color: red">${ "♥".repeat(arena.hp) }</span></h4>
                <hr>
                <div>
                    <button type="button" @click="attack" class="btn btn-danger">attack</button>
                    <button type="button" @click="defend" class="btn btn-warning">defend</button>
                </div>
            </div>
        </div>
    </div>
        <div>

        </div>
    </section>

{% endblock %}

{% block script %}

<script>


let coin = 100,health=100;
function init() {
    let tc = localStorage.getItem("coin");
    if (tc){
        coin = parseInt(tc);
    }else{
        localStorage.setItem("coin",100);
    }
    let th = localStorage.getItem("health");
    if(th){
        health = parseInt(th);
    }else{
        localStorage.setItem("health",100);
    }
}
init();

let app = new Vue({
    "el":"#vueApp",
    mounted:function() {
        this.random();
    },
    data:{
        coin:coin,
        word:"",
        word_cost:5,
        health:health,
        arena:"",
        interpretation:{
            query:"",
            basic:{
                'us-phonetic':"",
                explains:[]
            },
            translation:[]
        },
    },
    methods:{
        add_words:function () {
            let that = this;
            if (that.coin < that.word_cost){
                return
            }
            if(!that.word){
                return
            }

            that.$http.post("{% url "todo:api_words" %}", {word:that.word})
                .then(res=>{
                    that.arena=res.body;
                    that.getInterpretation();
                    });

            that.coin -= that.word_cost;
            that.word = "";
            localStorage.setItem("coin",that.coin);
            $('#add_word').modal('hide')
        },
        attack:function () {
            let that = this;
            that.arena.hp -= 1;
            that.$http.post("words/{}/".format(that.arena['id']),that.arena)
                .then(res=>{
                    that.health += 1;
                    that.coin += 1;
                    that.random();
                });
            localStorage.setItem("health",this.health);
        },
        defend:function () {
            let that = this;
            that.arena.hp += 1;
            that.$http.post("words/{}/".format(that.arena['id']),that.arena)
                .then(res=>{
                    that.random();
                    that.health -= 1;
                });
            localStorage.setItem("health",this.health);
        },
        random:function () {
            let that = this;
            that.$http.get("{% url "todo:words_random" %}")
                .then(res=>{
                    that.arena=res.body[0];
                    that.getInterpretation()
                })
        },
        getInterpretation:function(){
            let that = this;
            that.$http.post("{% url "api:translate" %}",{word:that.arena.word})
                .then(
                    res=>{
                        that.interpretation = res.body
                    }
                )
        },
        clearInterpretation:function () {
            this.interpretation = ""
        },
        audio_play:function () {
            let node = $("#audio")[0];
            node.play()
        }
    },
    computed:{

    },
})
</script>
{% endblock %}