api/urls.py
# !/usr/bin/env python 3
# encoding: utf-8
# url.py create by zander on 2017/9/6 10:24

from django.conf.urls import url

from . import views, api

urlpatterns = [
    url(r'^translate/$',api.Translation.as_view(), name='translate'),
    url(r'^translatev2/$',api.TranslationV2.as_view(), name='translatev2'),

]

djsite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.shortcuts import render


def index(request):
    return render(request, "todo.html")


urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'^admin/', admin.site.urls),
    url(r'^spider/', include('spider.urls', namespace="spider")),
    url(r'^todo/', include('todo.urls', namespace="todo")),
    url(r'^nlp/', include('nlp.urls', namespace="nlp")),
    url(r'^mining/', include('mining.urls', namespace="mining")),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^api/', include('api.urls', namespace="api")),
]

todo/urls.py
# !/usr/bin/env python 3
# encoding: utf-8
# urls.py create by zander on 2017/6/30 11:21
from django.conf.urls import url

from . import views
from . import api

urlpatterns = [
    url(r'^api_test$', views.api_test, name='api_test'),
    url(r'^references$', views.references, name='references'),
    url(r'^nlp', views.api_test, name='nlp'),
    url(r'^music$', views.music, name='music'),
    url(r'^css', views.css, name='css'),
    url(r'^q$', views.question, name='question'),
    url(r'^keyboard$', views.keyboard, name='keyboard'),
    url(r'^search$', views.todoFilter, name='search'),
    url(r'^words_hunter', views.words_hunter, name='words_hunter'),
    url(r'^api_words/$', api.WordsViewSet.as_view(),name="api_words"),
    url(r'^words/(?P<pk>[0-9]+)/$', api.WordDetail.as_view(),name="api_detail"),
    url(r'^words_random/$', api.WordsRandom.as_view(),name="words_random"),
    url(r'^questions/$', api.QuestionList.as_view(),name="questions"),
    url(r'^question/(?P<pk>[0-9]+)/$', api.GetOrUpdateQuestion.as_view(),name="get_update_question"),
    url(r'^last_question/$', api.LastQuestion.as_view(),name="last_question"),
    url(r'^create_question/$', api.CreateQuestion.as_view(),name="create_question"),
    url(r'^list/$', api.TodoList.as_view(),name="todo_list"),
    url(r'^new_todo/$', api.NewTodo.as_view(),name="new_todo"),
    url(r'^(?P<pk>[0-9]+)/$', api.GetOrUpdateTodo.as_view(),name="get_update_todo"),
    url(r'^delete_todo/(?P<pk>[0-9]+)/$', api.DeleteTodo.as_view(),name="delete_todo"),
]

todo/models.py
from django.db import models


# Create your models here.


class Todo(models.Model):
    content = models.CharField(verbose_name="Content", max_length=255)
    # in_time = models.DateTimeField(verbose_name="In Time", auto_created=True)
    create_time = models.DateTimeField(verbose_name="Create", auto_now_add=True)
    # edit_time = models.DateTimeField(verbose_name="Edit Time", auto_now=True)
    # level = models.SmallIntegerField(verbose_name="Level", default=3)
    state = models.BooleanField(verbose_name="State", default=False)
    # remarks = models.CharField(verbose_name="Remarks", max_length=1024, null=True)


class Question(models.Model):
    # 未make ，make之后删除该注释，，长度限制(i)，，markdown(i)
    desc = models.CharField(verbose_name="问题", max_length=255)
    in_time = models.DateTimeField(verbose_name="添加时间", auto_now_add=True)
    re_time = models.DateTimeField(verbose_name="解决时间", auto_now=True)
    state = models.BooleanField(verbose_name="状态", default=False)
    answer = models.CharField(verbose_name="答案", max_length=255,null=True,blank=True)

    # class Child(models.Model):
    #     parent = models.ForeignKey(Todo,verbose_name="Todo")
    #     content = models.CharField(verbose_name="Content", max_length=255)

    #
    # class Article(models.Model):
    #     content = models.TextField(verbose_name="内容", max_length=2048)
    #     in_date = models.TimeField(verbose_name="创建日期", auto_created=True)
    #     type = models.ForeignKey(ArticleType, verbose_name="类别")
    #
    #
    # class ArticleType(models.Model):
    #     name = models.CharField(verbose_name="分类名称", max_length=16)
    #     intro = models.CharField(verbose_name="简介", max_length=32, null=True)


class Words(models.Model):
    word = models.CharField(verbose_name="word", max_length=32, unique=True)
    level = models.IntegerField(verbose_name="level", default=1)
    hp = models.IntegerField(verbose_name="hp", default=5)

todo/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from .models import Todo, Words
from django.http import HttpResponse
import json
# Create your views here.


class IndexView(generic.ListView):
    template_name = "todo.html"
    context_object_name = "todo_list"

    def get_queryset(self):
        # fil = {
        #
        # }
        # if 'state' in self.request.GET:
        #     s = self.request.GET['state']
        #     fil['state'] = s == 'true'
        # if 'level' in self.request.GET:
        #     fil['level'] = self.request.GET['level']
        return Todo.objects.order_by('-create_time').all()


# API methods


def todoFilter(request):

    if request.is_ajax():
        # Todo.objects.filter().all()
        return HttpResponse()


def words_hunter(request):
    return render(request,"todo/words.html")


def api_test(request):

    return render(request,"todo/api_test.html")


def nlp(request):
    return render(request, "todo/nlp.html")


def references(request):
    return render(request, "todo/references.html")


def music(request):
    return render(request, "todo/music.html")


def question(request):
    return render(request,"todo/1-Q.html")


def keyboard(request):
    return  render(request, "todo/keyboard.html")

def css(request):
    return  render(request, "todo/css.html")

templates/index.html
{% extends "base/base.html" %}

{% block mainbody %}
    {% csrf_token %}
    <section class="container" style="background: white" id="vueApp">
        <div class="row">
            <div class="col-md-11 col-md-offset-1 time-line" style="min-height: 80px">
                <div class="col-md-3">
                    <button class="btn btn-info" data-toggle="modal" data-target="#newTodo">
	                    New Task
                    </button>
                <div class="modal fade" id="newTodo" tabindex="-1" role="dialog" aria-labelledby="newTodoLabel" aria-hidden="true">
	                <div class="modal-dialog">
		                <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                    &times;
                                </button>
                                <h4 class="modal-title" id="newTodoLabel">
                                    Create New Task
                                </h4>
                            </div>
                            <div class="modal-body">
                                <div class="form-horizontal" role="form">
                                    <div class="form-group">
                                        <label for="newTaskContent" class="col-md-2 control-label">Content :</label>
                                        <div class="col-md-10">
                                            <input id="newTaskContent" type="text" class="form-control" v-model="todo.content" placeholder="按下Enter键完成输入">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="taskLevels" class="col-md-2 control-label">Level :</label>
                                        <div class="col-md-2">
                                            <select id="taskLevels" class="form-control" v-model="todo.level">
                                                <option value="1">1</option>
                                                <option value="2">2</option>
                                                <option value="3">3</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal"><i class="icon-reply"></i>Cancel</button>
                                <button type="button" id="todoSubmit" class="btn btn-default" data-dismiss="modal" v-on:click="new_todo" >
                                    <i class="icon-ok">Ok</i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>

                </div>

                <div class="col-md-3">
                    <div class="form-inline">
                        <label class="control-label">状态:</label>
                        <select v-model="search.state" title="状态" v-on:change="filter" class="form-control">
                            <option value=""></option>
                            <option value="true">已完成</option>
                            <option value="false">未完成</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-inline">
                        <label for="" class="control-label">Level:</label>
                        <select class="form-control" v-model="search.level" title="" v-on:change="filter">
                            <option></option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-md-11 col-md-offset-1 time-line" v-for="(todo,index) in todos">
                <div class="todo-icon">
                    <input title="" type="checkbox" class="hidden"  v-model="todo.state" v-on:change="change_state(index)"/>
                    <a href="javascript:" style="text-decoration:none;">
                        <i class="icon-2x" :class="{'text-danger':todo.level==1,'text-warning':todo.level==2,'text-info':todo.level==3,'icon-ok-circle' : todo.state==true, 'icon-circle-blank' : todo.state==false}"> </i>
                    </a>
                </div>
                <div class="panel" :class="{'panel-danger':todo.level==1,'panel-warning':todo.level==2,'panel-info':todo.level==3}">
                    <div class="panel-heading">
                        <div class="form-inline">
                            <span>${ todo.inTime }</span>
                            <a href="javascript:" class="" title="Remarks" data-container="body" data-toggle="popover" data-placement="bottom" :data-content="todo.remarks">
                                Remarks
                            </a>
                        </div>

                    </div>
                    <div class="panel-body">
                        <div class="form-inline">
                            <input type="text"  class="form-control hidden" v-model="todo.content" title="">
                            <span class="todo-header" style="font-size: 1.5em">${ todo.content }</span>
                            <a href="javascript:" class="todo-check hidden"><i class="icon-ok"></i></a>
                            <a href="javascript:" class=""><i class="icon-pencil todo-edit"></i></a>
                        </div>
                        <div>
                            <ul class="list-group">
                                <li class="list-group-item" v-for="(child, item_index) in todo.child">${ item_index + 1 }: ${ child.content }</li>
                                <li class="list-group-item"><input title="add_child" :id="'item'+index" placeholder="添加子任务(Enter完成)" v-on:keyup="add_child(index, todo.id)"  type="text" style="max-width: 40%" class="form-control child_input"></li>
                                <li class="list-group-item">
                                    <a href="javascript:" v-on:click="add_child(index,todo.content)"><i class="icon-plus"></i>add detail</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-11 col-md-offset-1 time-line" style="min-height: 70px">
            </div>
        </div>
    </section>
{% endblock %}

{% block footer %}
<script>
    let href = window.location.href;

    function getParameter(name) {
        let query = href.split("?");
        if (query.length > 1){
            query = query[1]
        }else{
            return ""
        }
        let reg = new RegExp("(^|&)"+ name +"=([^&]*)(&|$)");
        let r = query.match(reg);
        if (r && r[2]){
            return r[2]
        }
        return ""
    }

    let  pagerData = [
        {% for todo in todo_list %}
            {
                id:"{{ todo.id }}",
                inTime:"{{ todo.in_time|date:"Y/m/d H:i" }}",
                content:"{{ todo.content}}",
                level:"{{ todo.level }}",
                state:"{{ todo.state|lower }}" === "true",
                remarks:"{{ todo.remarks }}",
                child:[
                {% for foo in todo.child_set.all %}
                    {
                        content:"{{ foo.content }}"
                    },
                {% endfor %}
                ]
            },
        {% endfor %}
    ];
    let token = $("[name='csrfmiddlewaretoken']").val();
    $(function () {
        $("a").find("i.todo-edit").on('click',function () {

            let par = $(this).parent().parent();
            par.find("input").removeClass("hidden");
            par.find(".todo-check").removeClass("hidden");
            par.find(".todo-header").addClass("hidden");
        });
        $("a").find("i.icon-ok").on('click',function () {
            let par = $(this).parent().parent();
            par.find("input").addClass("hidden");
            par.find(".todo-check").addClass("hidden");
            par.find(".todo-header").removeClass("hidden");
        });
        $("#newTaskContent").keyup(function () {
            if (event.which === 13 && app.todo.content!==""){
                $("#todoSubmit").click();
                app.new_todo()
            }
        });
        $("#vueApp").on("click",".todo-icon a",function () {
            $(this).parent().find(":checkbox").click()
        });
        $("[data-toggle='popover']").popover();

        $(".child_input").on('keyup',function () {
            if (event.which === 13){
{#                console.log($(this).val())#}
                app.add_child($(this).attr("id"),$(this).val())
            }

        })
    });

    let app = new Vue({
        el:"#vueApp",
        data:{
            todos:pagerData,
            todo:{
                inTime:"",
                content:"",
                level:3,
                state:false
            },
            search:{
                inTime:"",
                level:getParameter('level'),
                state:getParameter('state')
            }
        },
        methods:{
            new_todo:function () {
                let that = this;
                $.post({
                    url:"{% url "todo:ajax_add" %}" ,
                    data:{
                        todo:{
                            content:that.todo.content,
                            level:that.todo.level
                        },
                        csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val()
                    },
                    success:function (rep) {
                        let rd = JSON.parse(rep);
                        that.todo.inTime = rd.inTime;
                        that.todos.unshift(that.todo);
                        that.todo = {
                            inTime:"",
                            content:"",
                            level:3,
                            state:false
                        }
                    },
                    error:function (rep) {
                        console.log("Something error")
                    }
                });
            },
            save_todo:function (index) {


            },
            new_child:function () {

            },
            add_child:function (index, parent_id) {
                let that = this;
                let node = $(`#item${index}`);
                if(event.which === 13 && node.val()){
                    $.post({
                        url:"{% url "todo:ajax_add_child" %}",
                        data : {
                            child:{
                                parent_id : parent_id,
                                content : node.val()
                            },
                            csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val()
                        },
                        success:function (res) {
                            that.todos[index].child.push({content:node.val()});
                            node.val("")
                        },
                        error:function (res) {
                            console.log(res)
                        }

                    })


                }
            },
            change_state:function (index) {
                let that = this;
                $.post({
                    url:"{% url "todo:ajax_change_state" %}",
                    data:{
                        id:that.todos[index].id,
                        state:that.todos[index].state,
                        csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val()
                    },
                    success:function (res) {
                        console.log(res)
                    },
                    error:function (res) {

                    }
                })
            },
            filter:function () {
                let query = "";
                if (this.search.state){
                    query += 'state='+this.search.state
                }
                if (query){
                    query += "&"
                }
                if (this.search.level){
                    query += 'level='+this.search.level
                }

                window.location.href = "./?"+query
            },
        },
        watch:{

        },
        computed:{

        }
    })

</script>
{% endblock %}

templates/todo.html
{% extends "base/base.html" %}

{% block style %}
<style>
body{
    background: #f5f5f5;
}
.todo-header{
    text-align: center;
}
.todo-header h1{
    color: lightcoral;
    font-size: 8rem;
}
.new-todo{
    width: 100%;
    padding: 16px 16px 16px 60px;
    border: none;
    background: white  no-repeat;
    box-shadow: inset 0 -2px 1px rgba(0,0,0,0.03);
    outline: none;
    font-size: 1.5em;
{#    background: url("/static/imgs/favicon.ico") no-repeat;#}
}

.main{
    background: white;
{#    text-align: center;#}
    margin: 0 auto;
}
.main ul{
    padding: 0;
}
.main li{
    list-style: none;
{#    padding: 10px;#}
    border-bottom: 1px solid #ededed;
    margin: 0;
    padding: 0;
    font-weight: 300;
    line-height: 60px;
    font-size: 1.5em;
}
.main li:first-child{
    border-top: 1px solid #ededed;
}
.todo-content{
    word-break: break-all;
    white-space: normal;
    overflow: hidden !important;
    text-overflow: ellipsis !important;
    padding: 16px 50px;
    margin-bottom: 0;
    line-height: normal;
}
.main .toggle{
{#    float: left;#}
    position: absolute;
    left: 10px;
    text-decoration-line: none;
    font-size: 1.2em;
    padding: 0 20px 0 20px;
    color: #9d9d9d;
    font-weight: 200;
}
.todo-remove{
    display: none;
    position: absolute;
    right: 20px;
    color: pink;
    transition: color 0.2s ease-out;
    border: none;
    background: none;
    outline: none;
}
.todo-remove:hover{
    color: tomato;
}

.main li:hover .todo-remove{
    display: block;
}
.todo-body{
    width: 40%;
    margin: 0 auto;
}
.todo-complete{
    color: #d9d9d9;
    text-decoration: line-through;
}
.sign{
    position: absolute;
    top: 120px;
    height: 60px;
    left: 30px;
    background: none;
    border: none;
    outline: none;
}
.sign i{
    font-size: 2em;
    color: #d9d9d9;
}
.filter{
    border: 1px solid transparent;
    background:none;
    padding: 0 10px;
    outline: none;
}
.filter:hover{
    background: none;
    border: 1px solid rgba(175, 47, 47, 0.1);
}
.filter-wrap{
    padding: 10px 0 10px 20px ;
{#    height: 60px;#}
}
.filter-group{
    padding-left: 80px;
    display: inline-block;
}
.active{
    border: 1px solid rgba(175, 47, 47, 0.4);
    background: none;
}
ul{
    margin-bottom: 0;
}
</style>
{% endblock %}

{% block body_class %}

{% endblock %}

{% block mainbody %}
<section class="container" id="vueApp">
    <div class="row todo-body">
        <div class="col-md-12">
            <header class="todo-header">
                <h1>todos</h1>
                <input type="text" class="new-todo" autocomplete="off" v-model="newTodo.content" @keyup.13="add" autofocus placeholder="What`s need to be done?">
                <button type="button" class="sign" v-show="todos.length"><i class="icon-angle-down"></i></button>
            </header>
            <div class="main">
                <ul>
                    <li v-for="(todo,index) in visible_todos">
                        <a href="javascript:" class="toggle" @click="toggle(index)"><i :class="{'icon-ok-circle':todo.state,'icon-circle-blank':!todo.state}"></i></a>
                        <button type="button" class="todo-remove" @click="remove(index)"><i class="icon-remove"></i></button>
                        <p class="todo-content" :class="{'todo-complete':todo.state}">${ todo.content }</p>
                    </li>
                </ul>
                <section class="filter-wrap" v-show="todos.length">
                    <span><strong>${ left }</strong> item left</span>
                    <div class="filter-group">
                        <input type="radio" hidden id="all" value="all" v-model="visible_state">
                        <label class="filter" :class="{'active':visible_state == 'all'}" for="all">All</label>
                        <input type="radio" hidden id="active" value="active" v-model="visible_state">
                        <label class="filter" :class="{'active':visible_state == 'active'}" for="active">Active</label>
                        <input type="radio" hidden id="complete" value="complete" v-model="visible_state">
                        <label class="filter" :class="{'active':visible_state == 'complete'}" for="complete">Complete</label>
                    </div>
                </section>
            </div>
        </div>
    </div>
</section>

{% endblock %}

{% block footer %}
    <footer>

    </footer>
    <script>
        let app = new Vue({
            el:"#vueApp",
            mounted:function () {
                this.list()
            },
            data:{
                todos:[],
                newTodo:{
                    content:"",
                    state:false
                },
                visible_state:"all"
            },
            methods:{
                add:function () {
                    let that = this;
                    let content = that.newTodo;
                    if(!this.newTodo.content){
                        return
                    }
                    that.$http.post("{% url "todo:new_todo" %}",that.newTodo)
                        .then(res=>{
                            that.todos.unshift(res.body);
                            that.newTodo.content = ""
                        });

                },
                remove:function (index) {
                    let that = this;
                    let todo = that.todos[index];
                    that.$http.delete("todo/delete_todo/{}/".format(todo.id),todo)
                        .then(res=>{
                            that.todos.remove(index)
                        });
                },
                toggle:function(index){
                    let that = this;
                    let todo = that.todos[index];
                    let id = todo.id;
                    todo.state = !todo.state;
                    that.$http.post("todo/{}/".format(id),todo)
                        .then(res=>{
                            todo = res.body
                        });
                },
                list:function () {
                    let that = this;
                    that.$http.get("{% url "todo:todo_list" %}")
                        .then(res=>{
                            that.todos = res.body
                        })
                }
            },
            computed:{
                left:function () {
                    let wt = this.todos.filter(function (x) {
                        return !x.state
                    });
                    return wt.length
                },
                visible_todos:function () {
                    if (this.visible_state === 'all'){
                        return this.todos.filter(x=>1)
                    }else if(this.visible_state === 'active'){
                        return this.todos.filter(x=>!x.state)
                    }else if(this.visible_state=== 'complete'){
                        return this.todos.filter(x=>x.state)
                    }

                }
            }
        })
    </script>
{% endblock %}