api/urls.py
# !/usr/bin/env python 3
# encoding: utf-8
# url.py create by zander on 2017/9/6 10:24

from django.conf.urls import url

from . import views, api

urlpatterns = [
    url(r'^translate/$',api.Translation.as_view(), name='translate'),
    url(r'^translatev2/$',api.TranslationV2.as_view(), name='translatev2'),

]

blog/urls.py
# !/usr/bin/env python 3
# encoding: utf-8
# urls.py create by zander on 2017/8/2 12:51

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', view=views.IndexView.as_view(), name="index"),
    url(r'^create$', view=views.create, name="create"),
    # url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<article_id>[0-9]+)/$', views.detail,name="detail")
]

djsite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.shortcuts import render


def index(request):
    return render(request, "todo.html")


urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'^admin/', admin.site.urls),
    url(r'^spider/', include('spider.urls', namespace="spider")),
    url(r'^todo/', include('todo.urls', namespace="todo")),
    url(r'^nlp/', include('nlp.urls', namespace="nlp")),
    url(r'^mining/', include('mining.urls', namespace="mining")),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^api/', include('api.urls', namespace="api")),
]

mining/urls.py
# !/usr/bin/env python 3
# encoding: utf-8
# urls.py create by zander on 2017/7/21 14:51

from django.conf.urls import url

from . import views, api

urlpatterns = [
    url(r'^resource$', view=views.IndexList.as_view(), name='resource'),
    url(r'^spider$', view=views.ProjectList.as_view(), name='spider'),
    url(r'^detail$', view=views.projectDetail, name='detail'),
    url(r'^crawl$', view=views.crawl, name='crawl'),
    url(r'^csv_download$', view=views.csv_download, name='csv_download'),
    url(r'^pic_upload', view=views.pic_upload, name='pic_upload'),
    url(r'^resource_create$', view=api.ResourceCreate.as_view(),name='resource_create'),
    # url(r'^resource_create$', view=api..as_view(),name='resource_create'),
    url(r'^type_list', view=api.TypeList.as_view(),name='type_list'),
    url(r'^type/(?P<pk>[0-9]+)/', view=api.TypeDetail.as_view(),name='type_detail')

]

spider/urls.py
# !/usr/bin/env python 3
# encoding: utf-8
# urls.py create by zander on 2017/6/20 11:55
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^test$', views.test, name='test'),
]

spider/models.py
from django.db import models
# Create your models here.


class Headers(models.Model):
    content_type = models.CharField(verbose_name="Content Type", max_length=32, null=True, blank=True),
    user_agent = models.CharField(verbose_name="User-Agent", max_length=255, null=True, blank=True,
                                  default='Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, '
                                          'like Gecko) Chrome/59.0.3071.115 Safari/537.36')
    accept = models.CharField(verbose_name="Accept", max_length=64, null=True, blank=True)
    accept_encoding = models.CharField(verbose_name="Accept-Encoding",max_length=64, null=True, blank=True)
    accept_language = models.CharField(verbose_name="Accept-Language", max_length=64, null=True, blank=True)
    pass


class Setting(models.Model):
    name = models.CharField(verbose_name="识别码", max_length=32)
    headers = models.ForeignKey(Headers,verbose_name="请求头")
    time_out = models.IntegerField(verbose_name="超时时间(S)",null=True,blank=True)


class Project(models.Model):
    name = models.CharField(verbose_name="项目名称", max_length=32)
    setting = models.ForeignKey(Setting, verbose_name="设置方案")
    create_date = models.TimeField(verbose_name="创建时间", auto_now_add=True)
    pass


class Urls(models.Model):
    pass


class Column(models.Model):
    project = models.ForeignKey(Project, verbose_name="项目名称")
    name = models.CharField(verbose_name="列名称")

    pass


class NextPager(models.Model):
    pass


class ItemRule(models.Model):
    pass


class UrlRule(models.Model):
    pass


class Task(models.Model):
    STATE_CHOICE = (
        (0, '新建'),
        (1, '完成'),
        (2, '失败')
    )
    METHODS = (
        ('get', 'GET'),
        ('post', 'POST')
    )
    project = models.ForeignKey(Project, verbose_name="项目名称")
    url = models.CharField(verbose_name="网址",max_length=255)
    state = models.IntegerField(verbose_name="状态", choices=STATE_CHOICE,default=0)
    in_time = models.TimeField(verbose_name="in time", auto_now_add=True)
    method = models.CharField(verbose_name="类型", max_length=10, choices=METHODS, default='get')
    params = models.CharField(verbose_name="参数", max_length=255, null=True, blank=True)
    data = models.CharField(verbose_name="数据", max_length=255, null=True, blank=True)
    cookie = models.CharField(verbose_name="cookie", max_length=255, null=True, blank=True)
    session = models.CharField(verbose_name="session", max_length=255, null=True, blank=True)

spider/views.py
from django.shortcuts import render
from dwebsocket.decorators import accept_websocket,require_websocket
from django.http import HttpResponse
# Create your views here.
import time
import json
from django.db import transaction
from bs4 import BeautifulSoup
import requests
from scrapy.selector import Selector
from django.views import generic
import os


def test(request):
    if request.method == "GET":
        return render(request, "spider/test.html")
    else:
        method = 'get'
        url = request.POST['url']
        rule = request.POST['rule']
        r_m = request.POST['method']
        extract = request.POST['extract']
        headers = {
            'User-Agent':'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36',
            'Accept-Language':'zh-CN,zh;q=0.8',
            'Accept':'application/json, text/javascript, */*; q=0.01',
            'Accept-Encoding':'gzip, deflate, br'
        }

        res = requests.request(method=method,url=url,headers=headers)
        res.encoding = 'utf-8'

        se = Selector(response=res)

        result = getattr(getattr(se, r_m)(rule), extract)()
        d = {
            "html": res.text,
            "result": result
        }
        return HttpResponse(json.dumps(d))

spider/templates/spider/add.html
{% extends "base/base.html" %}

{% block mainbody %}
    <div class="container">
        <form id="controlForm" method="post" action="{% url 'spider:add' %}">
            {% csrf_token %}
            <div class="row">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <span>Main Info</span>
                        <div class="pull-right btn-group btn-group-sm">
                            <button type="button" class="btn btn-success"><i class="icon-check"></i>Validate</button>
                            <button type="button" class="btn btn-success"><i class="icon-save"></i>Submit</button>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="">Name:</label>
                                <input id="" name="name" v-vi:requried  type="text" v-validate="'required'" :class="{'form-control': true, 'input-danger': errors.has('name') }" v-model="project.name" title="" :placeholder="errors.first('name')"/>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label" for="">Allowed domains:</label>
                                <input id="" name="allowedDomains"  type="text" v-validate="'required'" :class="{'form-control': true, 'input-danger': errors.has('allowedDomains') }" v-model="project.allowed_domains" title="allowedDomains" :placeholder="errors.first('allowedDomains')"/>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="">Allow URL:</label>
                                <input id="" name="allowUrl"  type="text" v-validate="'required'" :class="{'form-control': true, 'input-danger': errors.has('allowUrl') }" v-model="project.allow_url" title="allow url" :placeholder="errors.first('allowUrl')"/>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="">Allow URL:</label>
                                <input type="text" class="form-control" v-model="project.columns" title="allow url">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Start URLs
                    </div>
                    <div class="panel-body">
                        <div class="col-md-12">
                            <table class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>URL</th>
                                    <th>删除？</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr v-for="(url,index) in urls">
                                    <td>
                                        <input id="" :name="url_header+index"  type="text" v-validate="'required'" :class="{'form-control': true, 'input-danger': errors.has('url0') }" v-model="url.link" title="url" :placeholder="errors.first('url')"/>
{#                                        <input type="text" name="project_url" class="form-control" v-model="url.link"/>#}
                                    </td>
                                    <td>
                                        <a href="javascript:" v-on:click="del_url(index)"><i class="icon-minus text-danger"></i></a>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2">
                                        <a href="javascript:" v-on:click="add_url"><i class="icon-plus"></i>新增一行</a>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="panel panel-success">
                    <div class="panel-heading">
                        Item Rules
                    </div>
                    <div class="panel-body">
                        <div class="col-md-12">
                            <table class="table table-bordered  table-striped">
                                <thead>
                                <tr>
                                    <th>Column</th>
                                    <th>Rule</th>
                                    <th>Method</th>
                                    <th>Extract</th>
                                    <th>Del?</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr v-for="(rule,index) in rules">
                                    <td><input type="text" name="project_url" class="form-control" title="column" v-model="rule.column"/></td>
                                    <td><input type="text" name="project_url" class="form-control" title="rule" v-model="rule.rule"/></td>
                                    <td>
                                        <select class="form-control" title="method" v-model="rule.method">
                                            <option value="css">css</option>
                                            <option value="xpath">xpath</option>
                                        </select>
                                    </td>
                                    <td>
                                        <select class="form-control" title="extract" v-model="rule.extract">
                                            <option value="extract">extract</option>
                                            <option value="extract_first">extract_first</option>
                                        </select>
                                    </td>
                                    <td>
                                        <a href="javascript:" v-on:click="del_rule(index)"><i class="icon-minus text-danger"></i></a>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="5">
                                        <a href="javascript:" v-on:click="add_rule"><i class="icon-plus"></i>新增一行</a>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block footer %}
<script>

    let mv = new Vue({
        el:"#controlForm",
        data:{
            urls:[
                {link:""}
            ],
            rules:[
                {column:"",rule:"",method:"xpath",extract:"extract_first"}
            ],
            project:{
                name:"",
                allow_url:"",
                allowed_domains:"",
                columns:"",
                next_pager:""
            },
            parse_method:['css','xpath'],
            url_header:"url"

        },
        methods:{
            add_url:function () {
                this.urls.push({link:""})
            },
            del_url:function (index) {
                if (this.urls.length >1){
                    this.urls.splice(index,1)
                }
            },
            add_rule:function () {
                this.rules.push({column:"",rule:"",method:"css",extract:"extract_first"})
            },
            del_rule:function (index) {
                if (this.rules.length >1){
                    this.rules.splice(index,1)
                }
            },
            submit:function () {
                let that = this;
                let data = {
                    project:that.project,
                    csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val()
                };
                that.urls.forEach(function (item,index) {
                    data["urls["+index+"]"] = item
                });
                that.rules.forEach(function (item,index) {
                    data["rules["+index+"]"] = item
                });
                console.log(data)
                $.post({
                    url:"{% url 'spider:add' %}",
                    data:data,
                    success:function (res) {
                        console.log("success")
                    },
                    error:function (rep) {
                        console.log("Something error")
                    }
                })
            },
            validateBeforeSubmit() {
                this.$validator.validateAll().then(() => {
                    // eslint-disable-next-line
                    alert('From Submitted!');
                }).catch(() => {
                    // eslint-disable-next-line
                    alert('Correct them errors!');
                });
            }
        },
        watch:{
            rules:function () {
                let str = "";
                let that = this;
                that.rules.forEach(function (item) {
                    str += item.column
                });
            }
        }
    })
</script>
{% endblock %}

spider/templates/spider/detail.html
{% extends "base/base.html" %}

{% block mainbody %}
    <div class="container">
        <div class="row">
            <div class="panel panel-primary">
                <div class="panel-heading">Main info</div>
                <div class="panel-body">
                    <div class="col-md-4">
                        <div class="form-inline">
                            <label>Id:</label>
                            <span>{{ project.id }}</span>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-inline">
                            <label>Name:</label>
                            <span>{{ project.name }}</span>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="panel panel-success">
                <div class="panel-heading">Rules</div>
                <div class="panel-body">
                    <table class="table table-bordered table-striped table-responsive">
                        <thead>
                        <tr>
                            <th>Column</th>
                            <th>Rule</th>
                            <th>Method</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for rule in project.rules_set.all %}
                            <tr>
                                <td>{{ rule.column }}</td>
                                <td>{{ rule.rule }}</td>
                                <td>{{ rule.method }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block footer %}
<script>

</script>
{% endblock %}

spider/templates/spider/index.html
{% extends "base/base.html" %}

{% block mainbody %}
{% csrf_token %}
    <section class="container" id="vueApp">
        <div class="row">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <span>Operating area</span>
                    <div class="pull-right">
                        <div class="btn-group btn-group-sm">
                            <a href="{% url "spider:add" %}" class="btn btn-success"><i class="icon-plus"></i>New Project</a>
                            <button type="button" class="btn btn-info" v-on:click="ws_conn"><i class="icon-spinner"></i>Connect</button>
                            <button type="button" class="btn btn-info" v-on:click="ws_close"><i class="icon-warning-sign"></i>Close</button>
                            <button type="button" class="btn btn-success" v-on:click="crawl"><i class="icon-play"></i>Crawl</button>
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="SelectProject">Select Project</label>
                            <select id="SelectProject" class="form-control" v-model="project_id">
                                {% for project in project_list %}
                                    <option value="{{ project.id }}" data-columns="{{ project.columns }}">{{ project.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <span>Result List</span>
                </div>
                <div class="panel-body">
                    <div class="col-md-9">
                        <table class="table table-bordered table-striped">
                            <caption>Item:</caption>
                            <thead>
                            <tr>
                                <th v-for="col in columns">${ col }</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr v-for="item in items">
                                <td v-for="col in columns">${ item[col] }</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="col-md-3">
                        <label class="">Urls:</label>
                        <ul class="list-group">
                            <li class="list-group-item" v-for="url in urls">
                                <span class="icon-arrow-right"></span>
                                <span>url</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}
{% block footer %}
    <script>

        let app = new Vue({
            el:"#vueApp",
            data:{
                project_id:"",
                project_selectable:true,
                columns:['name','content'],
                items:[],
                urls:[
                    "baidu",
                    "douban"
                ]
            },
            watch:{
                project_id:function () {
                    let cols =  $("#SelectProject").find("option:selected").data("columns");
                    this.columns = cols.split(",")
                }
            },
            methods:{
                crawl:function () {
                    let that = this;
                    $.post({
                        url:"{% url "spider:crawl" %}",
                        data:{
                            csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val(),
                            project_id:that.project_id
                        },
                        success:function (res) {
                            console.log("success");

                        },
                        error:function (res) {
                            console.log("error")
                        }
                    })
                },
                ws_conn:function () {
                    let that = this;
                    if(window.ws){
                        window.ws.close()
                    }
                    let ws = new WebSocket("ws://" + window.location.host + "/spider/echo");
                    ws.onopen = function () {
                        console.log("WebSocket Connected")
                    };
                    ws.onmessage=function (msg) {
                        console.log(msg.data);
                        let jl = JSON.parse(msg.data);
                        that.$data.items.push(jl.data);
{#                        var jl = JSON.parse(msg.data);#}
{#                        if (that.items.length >=5){#}
{#                            that.items.shift()#}
{#                        }#}
{#                        that.items.push(jl)#}
                    };
                    ws.onclose=function (p1) {
                        console.log("WebSocket Closed")
                    };
                    ws.onerror = function (p1) {
                        console.log("SomeThing error...")
                    };
                    window.ws = ws
                },
                ws_close:function () {
                    if(window.ws){
                        window.ws.close()
                    }
                },
            }
        });
    </script>
{% endblock %}

spider/templates/spider/list.html
{% extends "base/base.html" %}

{% block mainbody %}
    <div class="container">
        <div class="row">
            <div class="panel panel-success">
                <div class="panel-heading">Project List</div>
                <div class="panel-body">
                    <table class="table table-bordered table-responsive table-striped">
                        <thead>
                        <tr>
                            <th>id</th>
                            <th>name</th>
                            <th>Opt</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for project in project_list %}
                            <tr>
                                <td>{{ project.id }}</td>
                                <td>{{ project.name }}</td>
                                <td><a href="{% url "spider:detail" project.id %}"><i class="icon-book"></i></a></td>
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

spider/templates/spider/test.html
{% extends "base/base.html" %}

{% block mainbody %}
    <div class="container" id="vueApp">
    {% csrf_token %}
        <div class="row">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Main info
                    <div class="pull-right">
                        <div class="btn-group">
                            <a href="http://scrapy-chs.readthedocs.io/zh_CN/latest/topics/selectors.html" class="btn btn-info btn-sm" target="_blank">选择器语法</a>
                            <button type="button" v-on:click="submit" class="btn btn-success btn-sm">Submit</button>
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="col-md-3">
                            <div class="form-group">
                                <label for="url">URL</label>
                                <input id="url" name="" type="text" class="form-control" title="" v-model="url"/>
                            </div>
                        </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label for="rule">Rule</label>
                            <input id="rule" name="" type="text" class="form-control" title="" v-model="rule"/>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label for="method">Method</label>
                            <select id="method" v-model="method" class="form-control">
                                <option v-for="m in methods">${ m }</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label for="extract">Extract</label>
                            <select id="extract" v-model="extract" class="form-control">
                                <option v-for="e in extracts">${ e }</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="panel panel-success">
                <div class="panel-heading">
                    Response
                </div>
                <div class="panel-body">
                    <div class="col-md-8">
                        <div class="form-group">
                            <label for="">Html</label>
                            <pre style="overflow: scroll;min-height: 200px;max-height: 600px">${ response }</pre>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="">Result</label>
                            <pre style="min-height: 200px;overflow-y: scroll;max-height: 600px">${ result }</pre>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block footer %}
 <script>
    let mv = new Vue({
        el:"#vueApp",
        data:{
            url:"https://movie.douban.com/",
            rule:"div.nav a::text",
            method:"css",
            methods:['css','xpath'],
            response:"",
            result:"",
            extract:"extract",
            extracts:['extract','extract_first']
        },
        methods:{
            submit:function () {
                let that = this;
                $.post({
                    url:"{% url 'spider:test' %}",
                    data:{
                        url:that.url,
                        rule:that.rule,
                        method:that.method,
                        extract:that.extract,
                        csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val()
                    },
                    success:function (response) {
                        let j = JSON.parse(response);
                        that.response = j['html'];
                        that.result = j['result']
                    },
                    error:function () {
                        console.log("error")
                    }
                })
            }
        }

    })

 </script>

{% endblock %}

spider/templates/spider/ws.html
<!DOCTYPE html>
<html>
<head>
    <title>django-websocket</title>
    <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
    <script type="text/javascript">//<![CDATA[
    $(function () {
        $('#connect_websocket').click(function () {
            if (window.s) {
                window.s.close()
            }
            /*创建socket连接*/
            var socket = new WebSocket("ws://" + window.location.host + "/parse/echo");
            socket.onopen = function () {
                console.log('WebSocket open');//成功连接上Websocket
            };
            socket.onmessage = function (e) {
                console.log('message: ' + e.data);//打印出服务端返回过来的数据
                $('#messagecontainer').prepend('<p>' + e.data + '</p>');
            };
            // Call onopen directly if socket is already open
            if (socket.readyState == WebSocket.OPEN) socket.onopen();
            window.s = socket;
        });
        $('#send_message').click(function () {
            //如果未连接到websocket
            if (!window.s) {
                alert("websocket未连接.");
            } else {
                window.s.send($('#message').val());//通过websocket发送数据
            }
        });
        $('#close_websocket').click(function () {
            if (window.s) {
                window.s.close();//关闭websocket
                console.log('websocket已关闭');
            }
        });

    });
    //]]></script>
</head>
<body>
<br>
<input type="text" id="message" value="Hello, World!"/>
<button type="button" id="connect_websocket">连接 websocket</button>
<button type="button" id="send_message">发送 message</button>
<button type="button" id="close_websocket">关闭 websocket</button>
<h1>Received Messages</h1>
<div id="messagecontainer">

</div>
</body>
</html>